version: 2.1

jobs:
  build:
    docker:
      - image: circleci/elixir:latest

    steps:
      - checkout

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: stats
